### ISSUE TITLE
meta.title not showing session description correctly

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#249]
see difference between rendered session title on draft and <title> tag:
![image](https://user-images.githubusercontent.com/9142942/176425518-5d4460a7-7e91-481a-a207-db58e53f2a05.png)

in this case page title (<title>) should say:
![image](https://user-images.githubusercontent.com/9142942/194270076-33058b9d-0761-4b57-b8a5-cbb2615ca473.png)

**Comment by slawciu** [comment]
I am working on it!

**Comment by tarnas14** [comment]
freshly created sessions have "null" as their title (both created and drafted):
![image](https://user-images.githubusercontent.com/9142942/196266743-67ee1eb7-5d76-42bd-b7ce-0cabaac86d46.png)
(when empty session name is saved - it correctly shows nothing)

requirements for correct session title presentation:
- [ ] for session in draft it should show "Draft in progress - Banning / Picking" (dependent on stage)
- [ ] for session in progress it should show: "session name (if present), point threshold, session date (if present), factions (if name not present)"
- [ ] for locked sessions with a winner it should show: "Winner: player name (faction), session name (if present), point threshold, session date (if present), factions (if name not present)"
