### ISSUE TITLE
victory points source validation

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#338]
when adding source of victory points, there should be validation of business rules:

- [ ] should not be able to add "custodian" multiple times
- [ ] "custodian" should not be available as a suggestion if there is "custodian" already selected
- [ ] should not be able to choose "sft" multiple times from the same faction (in a row, if you give someone sft from Muaat, then Muaat loses sft point, they can give it to someone else)
- [ ] should not be able to choose "crown of emphydia" multiple times
